# Generated by Django 5.0.3 on 2024-04-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_alter_category_name_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
